### ISSUE TITLE
Sicoob

### ISSUE THREAD

**Issue by nandodigi** [gildonei/unicred#4]
Boa tarde Gildonei
Vc já deu uma olhada na API do Sicoob, eles tem uma autorização com oAuth e até agora não entendi como funciona isso
Eles tem um site para desenvolvedores https://developers.sicoob.com.br/ 

Abração
Fernando Pereira

**Comment by gildonei** [comment]
OI Nando, Sicoob é um banco diferente da Unicred, são cooperativas diferentes, logo a plataforma de um não vai se aplicar a outro. Esta API que desenvolvi, é para emissão / registro de boleto bancário, já o link que vc passou do Sicoob, pelo que li a respeito serve apenas para consultas de informações sobre saldo e extrato.

**Comment by nandodigi** [comment]
Já dei uma olhada bem a fundo no site deles e após realizar o login ele libera para consulta de toda documentação
E temos condições de realizar tudo, registro, consulta, alterações e etc, abaixo é uma foto do menu de funções.
É super completo
![image](https://user-images.githubusercontent.com/48023241/106942862-6c08a200-6703-11eb-84b7-1a0a31800bf2.png)

Mas veja neste link https://developers.sicoob.com.br/#!/oauth2 a parte de autenticação, eu nunca tinha visto essa forma de autenticação oauth2.

**Comment by gildonei** [comment]
OI @nandodigi obrigado pelas referências, mas não entendi ainda a relação com a API Unicred, que é de outro banco.
Em que esta API deste projeto irá poder lhe ajudar com o Sicoob?

**Comment by nandodigi** [comment]
Pelo que entendi da documentação de tua Classe e da documentação da classe do Sicoob a diferença é a autenticação oauth que é necessária antes do envio. A minha questão é a seguinte, será que tem como adaptar a autenticação ao teu projeto ?

**Comment by gildonei** [comment]
OI @nandodigi, eu acredito que você consiga adaptar bastante coisa. Este projeto que desenvolvi, foi montado com base na API da Cielo - https://github.com/DeveloperCielo/API-3.0-PHP.

Eu baixei o projeto, removi as partes que não me interessavam, mantive os créditos para os códigos re-utilizados e cheguei neste código final.

Do mesmo modo, estou implementando uma lib para emissão de NFPS-e para a prefeitura de Floripa - https://github.com/gildonei/nfse-pmf (ainda em desenvolvimento) mas tomei este projeto como base, modifiquei a autenticação, criei novos métodos e estou seguindo em frente.

Como tenho clientes que utilizam o Sicoob, provavelmente em um futuro não muito distante, devo implementar algo para esta biblioteca que você citou, mas acredito que se vc baixar o projeto aqui e mudar a autenticação, o resto você consegue reaproveitar e modificar as pontualidades.

**Comment by nandodigi** [comment]
Amigão, agradeço sua resposta e vou tentar realizar essa adaptação. 
Acho que o seguinte código resolve o problema
https://gist.github.com/aaronpk/3612742
